dist: trusty
sudo: required
services:
 - docker

# Install latest Docker CE so we can use Dockerfile outside build context
addons:
 apt:
   packages:
     - docker-ce

# Install any dependencies, update Docker Compose to 1.23.2 so we can use Dockerfile outside build context
before_install:
- docker --version
- docker-compose --version
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker-compose --version

#install:

# Build development images for test
before_script:
 - docker build ./todo-view -f ./todo-view/Dockerfile.dev -t gravitonian/todo-view-test
 - docker build ./todo-cache-service -f Dockerfile.nodejs.dev -t gravitonian/todo-cache-service-test

# Run some tests
script:
 - docker run gravitonian/todo-view-test npm test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
 - docker run gravitonian/todo-cache-service-test npm test

after_success:
 # Build Production Images for deployment
 - docker-compose -f docker-compose.yml -f docker-compose.prod.yml build

 # Login to Docker Hub
 - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

 # Take the built production images and push to Docker Hub
 - docker-compose -f docker-compose.yml -f docker-compose.prod.yml push

